# Generated by Django 3.2.12 on 2022-04-23 04:16

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    state_operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Логин')),
                ('first_name', models.CharField(blank=True, max_length=32, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=32, verbose_name='Фамилия')),
                ('password', models.CharField(max_length=24)),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('photo', models.ImageField(blank=True, upload_to='photo_users/%Y/%m/%d/', verbose_name='Фото')),
                ('last_active_date', models.DateTimeField(verbose_name='Заходил последний раз')),
                ('ban', models.BooleanField(default=False, verbose_name='Бан')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'account_user',
                'ordering': ['username'],
            },
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        )
    ]