# Generated by Django 3.2.12 on 2022-04-25 03:46

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('expires', models.DateTimeField()),
                ('ip_addr', models.GenericIPAddressField(default='192.168.1.222')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            managers=[
                ('custom', django.db.models.manager.Manager()),
            ],
        ),
    ]
