# Generated by Django 3.2.12 on 2022-04-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='key',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
