# Generated by Django 3.2.12 on 2022-02-22 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AlterField(
            model_name='forum',
            name='last_change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_edit_date', models.DateTimeField(auto_now=True, verbose_name='Время последнего редактирования')),
                ('author', models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='forum.user', verbose_name='Автор')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='Форум')),
            ],
        ),
        migrations.CreateModel(
            name='MessageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.BooleanField(default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.user')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.message')),
            ],
            options={
                'unique_together': {('message', 'author')},
            },
        ),
        migrations.CreateModel(
            name='ForumRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.BooleanField(default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.user')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum')),
            ],
            options={
                'unique_together': {('forum', 'author')},
            },
        ),
    ]
