# Generated by Django 3.2.12 on 2022-04-09 04:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20220223_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156)),
            ],
        ),
        migrations.AlterModelManagers(
            name='forum',
            managers=[
                ('custom', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='forum',
            name='last_change_date',
        ),
        migrations.AddField(
            model_name='forum',
            name='url',
            field=models.SlugField(blank=True, verbose_name='Слаг'),
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='message',
            name='refer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='forum.message'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_users/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='author',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='forums', to='forum.user', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='messages', to='forum.user', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='forum.forum', verbose_name='Форум'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active_date',
            field=models.DateTimeField(verbose_name='Заходил последний раз'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('expires', models.DateTimeField()),
                ('ip_addr', models.GenericIPAddressField(default='192.168.1.222')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.user')),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='forum.category'),
        ),
    ]
