# Generated by Django 3.2.12 on 2022-04-23 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('forum', '0004_auto_20220409_0813'),
    ]

    database_operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.SlugField(default='about-us', max_length=24, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forum.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forum',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='url',
            field=models.SlugField(max_length=24, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='Форум'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.AlterModelTable(
            name='User',
            table='account_user',
        ),
    ]
    
    state_operations = [
            migrations.AddField(
                model_name='category',
                name='url',
                field=models.SlugField(default='about-us', max_length=24, unique=True, verbose_name='URL'),
            ),
            migrations.AlterField(
                model_name='forum',
                name='author',
                field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.user', verbose_name='Создатель'),
            ),
            migrations.AlterField(
                model_name='forum',
                name='category',
                field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forum.category'),
                preserve_default=False,
            ),
            migrations.AlterField(
                model_name='forum',
                name='is_published',
                field=models.BooleanField(default=False, verbose_name='Опубликовано'),
            ),
            migrations.AlterField(
                model_name='forum',
                name='url',
                field=models.SlugField(max_length=24, unique=True, verbose_name='URL'),
            ),
            migrations.AlterField(
                model_name='message',
                name='author',
                field=models.ForeignKey(default='deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='account.user', verbose_name='Автор'),
            ),
            migrations.AlterField(
                model_name='message',
                name='forum',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='Форум'),
            ),
            migrations.AlterField(
                model_name='messagerating',
                name='author',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            ),
            migrations.DeleteModel(
                name='Session',
            ),
            migrations.DeleteModel(
                name='User',
            ),
        ]
    
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, 
            state_operations=state_operations
        )
    ]